jobs:
  - name: pipelines-dv-manifest
    type: manifest
    steps:
     - IN: pipelines-dv-image
     - TASK: managed

  - name: deploy-pipelines-dv
    type: deploy
    steps:
      - IN: pipelines-dv-manifest
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade
